package cz.muni.fi.agentproject;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * This class represents a secret agent. It's just a holder of few attributes like structure in C.
 *
 * @author  Wallecnik
 * @version 31.2.2015
 */
public class Agent {

    private Long id;
    private String name;
    private long born;

    private static final String AGENT_FORMAT_REGEX = "Agent\\{name='(" + Constants.AGENT_NAME_REGEX + ")', born=(\\d+)\\}";

    /**
     * Constructor for objects of class Agent.
     *
     * @param id          synthetic id of this Agent
     * @param name        name of this Agent
     * @param born        long value of time in miliseconds
     */
    public Agent(Long id, String name, long born) {
        this.id = id;
        this.name = name;
        this.born = born;
    }

    /**
     * Getters
     */

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public long getBorn() {
        return born;
    }

    /**
     * Setters
     */

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setBorn(long born) {
        this.born = born;
    }

    /**
     * Equals + hashCode methods
     */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Agent)) return false;

        Agent agent = (Agent) o;

        if (born != agent.born) return false;
        if (id != null ? !id.equals(agent.id) : agent.id != null) return false;
        if (name != null ? !name.equals(agent.name) : agent.name != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (int) (born ^ (born >>> 32));
        return result;
    }

    /**
     * Returns a brief description of this agent. Exact format is unspecified,
     * but the following may look typically like that:
     *
     * "Agent{name='John Doe', born=12345}"
     *
     * @return String representing this Agent
     */
    @Override
    public String toString() {
        return "Agent{" +
                "name='" + name + '\'' +
                ", born=" + born +
                '}';
    }

    //TODO: not tested
    /**
     * Returns a new instance of Agent described in the first parameter.
     * Format of the string is same as the string generated by this class's
     * toString() method.
     *
     * Method return a new instance of an Agent or null if format of the input
     * string was incorrect.
     *
     * @param agent String from which to read and generate new instance
     * @return      a new instance of Agent or null
     */
    public static Agent create(String agent) {
        Pattern pattern = Pattern.compile(AGENT_FORMAT_REGEX);
        Matcher matcher = pattern.matcher(agent);

        if (matcher.matches()) {
            matcher.find();
            String name = matcher.group();

            matcher.find();
            Long born = Long.parseLong(matcher.group());

            return new Agent(null, name, born);
        }

        return null;
    }

}



















